version: '2.3'
services:
  device-server:
    environment:
      PORT: '8888'
      ALLOWEDDOMAIN: 'http://localhost:5000,http://localhost:8888'
      DBCONSTRING: ''
  device-client:
    environment:
      REACT_APP_APIDOMAIN: 'http://localhost:8888'
